package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.g2p1;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table G2P1.
*/
public class g2p1Dao extends AbstractDao<g2p1, Long> {

    public static final String TABLENAME = "G2P1";

    /**
     * Properties of entity g2p1.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Eadg = new Property(1, Integer.class, "eadg", false, "EADG");
        public final static Property Insp = new Property(2, Integer.class, "insp", false, "INSP");
        public final static Property Audi = new Property(3, Integer.class, "audi", false, "AUDI");
        public final static Property Miem = new Property(4, Integer.class, "miem", false, "MIEM");
        public final static Property Prod = new Property(5, Integer.class, "prod", false, "PROD");
        public final static Property Cade = new Property(6, Integer.class, "cade", false, "CADE");
        public final static Property Cost = new Property(7, Integer.class, "cost", false, "COST");
        public final static Property Dese = new Property(8, Integer.class, "dese", false, "DESE");
        public final static Property Origen = new Property(9, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(10, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(11, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public g2p1Dao(DaoConfig config) {
        super(config);
    }
    
    public g2p1Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'G2P1' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'EADG' INTEGER," + // 1: eadg
                "'INSP' INTEGER," + // 2: insp
                "'AUDI' INTEGER," + // 3: audi
                "'MIEM' INTEGER," + // 4: miem
                "'PROD' INTEGER," + // 5: prod
                "'CADE' INTEGER," + // 6: cade
                "'COST' INTEGER," + // 7: cost
                "'DESE' INTEGER," + // 8: dese
                "'ORIGEN' INTEGER," + // 9: origen
                "'OBSER' TEXT," + // 10: obser
                "'ID_FORMULARIO' INTEGER);"); // 11: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'G2P1'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, g2p1 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer eadg = entity.getEadg();
        if (eadg != null) {
            stmt.bindLong(2, eadg);
        }
 
        Integer insp = entity.getInsp();
        if (insp != null) {
            stmt.bindLong(3, insp);
        }
 
        Integer audi = entity.getAudi();
        if (audi != null) {
            stmt.bindLong(4, audi);
        }
 
        Integer miem = entity.getMiem();
        if (miem != null) {
            stmt.bindLong(5, miem);
        }
 
        Integer prod = entity.getProd();
        if (prod != null) {
            stmt.bindLong(6, prod);
        }
 
        Integer cade = entity.getCade();
        if (cade != null) {
            stmt.bindLong(7, cade);
        }
 
        Integer cost = entity.getCost();
        if (cost != null) {
            stmt.bindLong(8, cost);
        }
 
        Integer dese = entity.getDese();
        if (dese != null) {
            stmt.bindLong(9, dese);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(10, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(11, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(12, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public g2p1 readEntity(Cursor cursor, int offset) {
        g2p1 entity = new g2p1( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // eadg
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // insp
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // audi
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // miem
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // prod
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // cade
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // cost
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // dese
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // origen
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // obser
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, g2p1 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEadg(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setInsp(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setAudi(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setMiem(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setProd(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setCade(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setCost(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setDese(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setOrigen(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setObser(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setId_formulario(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(g2p1 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(g2p1 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
