package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.g2p2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table G2P2.
*/
public class g2p2Dao extends AbstractDao<g2p2, Long> {

    public static final String TABLENAME = "G2P2";

    /**
     * Properties of entity g2p2.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Eadg = new Property(1, Integer.class, "eadg", false, "EADG");
        public final static Property Origen = new Property(2, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(3, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(4, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public g2p2Dao(DaoConfig config) {
        super(config);
    }
    
    public g2p2Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'G2P2' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'EADG' INTEGER," + // 1: eadg
                "'ORIGEN' INTEGER," + // 2: origen
                "'OBSER' TEXT," + // 3: obser
                "'ID_FORMULARIO' INTEGER);"); // 4: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'G2P2'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, g2p2 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer eadg = entity.getEadg();
        if (eadg != null) {
            stmt.bindLong(2, eadg);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(3, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(4, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(5, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public g2p2 readEntity(Cursor cursor, int offset) {
        g2p2 entity = new g2p2( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // eadg
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // origen
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // obser
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, g2p2 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEadg(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setOrigen(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setObser(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setId_formulario(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(g2p2 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(g2p2 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
