package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.g3p2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table G3P2.
*/
public class g3p2Dao extends AbstractDao<g3p2, Long> {

    public static final String TABLENAME = "G3P2";

    /**
     * Properties of entity g3p2.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cmdg = new Property(1, Integer.class, "cmdg", false, "CMDG");
        public final static Property Acfi = new Property(2, Integer.class, "acfi", false, "ACFI");
        public final static Property Lcdl = new Property(3, Integer.class, "lcdl", false, "LCDL");
        public final static Property Lmsi = new Property(4, Integer.class, "lmsi", false, "LMSI");
        public final static Property Lmsc = new Property(5, Integer.class, "lmsc", false, "LMSC");
        public final static Property Origen = new Property(6, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(7, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(8, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public g3p2Dao(DaoConfig config) {
        super(config);
    }
    
    public g3p2Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'G3P2' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CMDG' INTEGER," + // 1: cmdg
                "'ACFI' INTEGER," + // 2: acfi
                "'LCDL' INTEGER," + // 3: lcdl
                "'LMSI' INTEGER," + // 4: lmsi
                "'LMSC' INTEGER," + // 5: lmsc
                "'ORIGEN' INTEGER," + // 6: origen
                "'OBSER' TEXT," + // 7: obser
                "'ID_FORMULARIO' INTEGER);"); // 8: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'G3P2'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, g3p2 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer cmdg = entity.getCmdg();
        if (cmdg != null) {
            stmt.bindLong(2, cmdg);
        }
 
        Integer acfi = entity.getAcfi();
        if (acfi != null) {
            stmt.bindLong(3, acfi);
        }
 
        Integer lcdl = entity.getLcdl();
        if (lcdl != null) {
            stmt.bindLong(4, lcdl);
        }
 
        Integer lmsi = entity.getLmsi();
        if (lmsi != null) {
            stmt.bindLong(5, lmsi);
        }
 
        Integer lmsc = entity.getLmsc();
        if (lmsc != null) {
            stmt.bindLong(6, lmsc);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(7, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(8, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(9, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public g3p2 readEntity(Cursor cursor, int offset) {
        g3p2 entity = new g3p2( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // cmdg
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // acfi
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // lcdl
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // lmsi
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // lmsc
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // origen
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // obser
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, g3p2 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCmdg(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setAcfi(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setLcdl(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setLmsi(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setLmsc(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOrigen(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setObser(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setId_formulario(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(g3p2 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(g3p2 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
