package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.g3p5;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table G3P5.
*/
public class g3p5Dao extends AbstractDao<g3p5, Long> {

    public static final String TABLENAME = "G3P5";

    /**
     * Properties of entity g3p5.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Eadg = new Property(1, Integer.class, "eadg", false, "EADG");
        public final static Property Sein = new Property(2, Integer.class, "sein", false, "SEIN");
        public final static Property Fech = new Property(3, String.class, "fech", false, "FECH");
        public final static Property Hain = new Property(4, Integer.class, "hain", false, "HAIN");
        public final static Property Lanu = new Property(5, Integer.class, "lanu", false, "LANU");
        public final static Property Origen = new Property(6, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(7, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(8, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public g3p5Dao(DaoConfig config) {
        super(config);
    }
    
    public g3p5Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'G3P5' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'EADG' INTEGER," + // 1: eadg
                "'SEIN' INTEGER," + // 2: sein
                "'FECH' TEXT," + // 3: fech
                "'HAIN' INTEGER," + // 4: hain
                "'LANU' INTEGER," + // 5: lanu
                "'ORIGEN' INTEGER," + // 6: origen
                "'OBSER' TEXT," + // 7: obser
                "'ID_FORMULARIO' INTEGER);"); // 8: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'G3P5'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, g3p5 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer eadg = entity.getEadg();
        if (eadg != null) {
            stmt.bindLong(2, eadg);
        }
 
        Integer sein = entity.getSein();
        if (sein != null) {
            stmt.bindLong(3, sein);
        }
 
        String fech = entity.getFech();
        if (fech != null) {
            stmt.bindString(4, fech);
        }
 
        Integer hain = entity.getHain();
        if (hain != null) {
            stmt.bindLong(5, hain);
        }
 
        Integer lanu = entity.getLanu();
        if (lanu != null) {
            stmt.bindLong(6, lanu);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(7, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(8, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(9, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public g3p5 readEntity(Cursor cursor, int offset) {
        g3p5 entity = new g3p5( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // eadg
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // sein
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fech
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // hain
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // lanu
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // origen
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // obser
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, g3p5 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEadg(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSein(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setFech(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHain(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setLanu(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOrigen(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setObser(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setId_formulario(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(g3p5 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(g3p5 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
