package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table G3P8.
 */
public class g3p8 {

    private Long id;
    private Integer ldda;
    private String nive;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public g3p8() {
    }

    public g3p8(Long id) {
        this.id = id;
    }

    public g3p8(Long id, Integer ldda, String nive, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.ldda = ldda;
        this.nive = nive;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLdda() {
        return ldda;
    }

    public void setLdda(Integer ldda) {
        this.ldda = ldda;
    }

    public String getNive() {
        return nive;
    }

    public void setNive(String nive) {
        this.nive = nive;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
