package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P10P6.
 */
public class p10p6 {

    private Long id;
    private Integer fiprg;
    private Integer iprg;
    private Integer ipcd;
    private Integer cobs;
    private Integer sia;
    private Integer mac;
    private Integer maf;
    private Integer uee;
    private Integer mir;
    private Integer utl;
    private Integer mpps;
    private Integer pirg;
    private Integer mpta;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p10p6() {
    }

    public p10p6(Long id) {
        this.id = id;
    }

    public p10p6(Long id, Integer fiprg, Integer iprg, Integer ipcd, Integer cobs, Integer sia, Integer mac, Integer maf, Integer uee, Integer mir, Integer utl, Integer mpps, Integer pirg, Integer mpta, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.fiprg = fiprg;
        this.iprg = iprg;
        this.ipcd = ipcd;
        this.cobs = cobs;
        this.sia = sia;
        this.mac = mac;
        this.maf = maf;
        this.uee = uee;
        this.mir = mir;
        this.utl = utl;
        this.mpps = mpps;
        this.pirg = pirg;
        this.mpta = mpta;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFiprg() {
        return fiprg;
    }

    public void setFiprg(Integer fiprg) {
        this.fiprg = fiprg;
    }

    public Integer getIprg() {
        return iprg;
    }

    public void setIprg(Integer iprg) {
        this.iprg = iprg;
    }

    public Integer getIpcd() {
        return ipcd;
    }

    public void setIpcd(Integer ipcd) {
        this.ipcd = ipcd;
    }

    public Integer getCobs() {
        return cobs;
    }

    public void setCobs(Integer cobs) {
        this.cobs = cobs;
    }

    public Integer getSia() {
        return sia;
    }

    public void setSia(Integer sia) {
        this.sia = sia;
    }

    public Integer getMac() {
        return mac;
    }

    public void setMac(Integer mac) {
        this.mac = mac;
    }

    public Integer getMaf() {
        return maf;
    }

    public void setMaf(Integer maf) {
        this.maf = maf;
    }

    public Integer getUee() {
        return uee;
    }

    public void setUee(Integer uee) {
        this.uee = uee;
    }

    public Integer getMir() {
        return mir;
    }

    public void setMir(Integer mir) {
        this.mir = mir;
    }

    public Integer getUtl() {
        return utl;
    }

    public void setUtl(Integer utl) {
        this.utl = utl;
    }

    public Integer getMpps() {
        return mpps;
    }

    public void setMpps(Integer mpps) {
        this.mpps = mpps;
    }

    public Integer getPirg() {
        return pirg;
    }

    public void setPirg(Integer pirg) {
        this.pirg = pirg;
    }

    public Integer getMpta() {
        return mpta;
    }

    public void setMpta(Integer mpta) {
        this.mpta = mpta;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
