package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p10p5;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P10P5.
*/
public class p10p5Dao extends AbstractDao<p10p5, Long> {

    public static final String TABLENAME = "P10P5";

    /**
     * Properties of entity p10p5.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Flsd = new Property(1, Integer.class, "flsd", false, "FLSD");
        public final static Property Fel = new Property(2, Integer.class, "fel", false, "FEL");
        public final static Property Fip = new Property(3, Integer.class, "fip", false, "FIP");
        public final static Property Rapa = new Property(4, Integer.class, "rapa", false, "RAPA");
        public final static Property Dble = new Property(5, Integer.class, "dble", false, "DBLE");
        public final static Property Rpc = new Property(6, Integer.class, "rpc", false, "RPC");
        public final static Property Origen = new Property(7, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(8, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(9, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public p10p5Dao(DaoConfig config) {
        super(config);
    }
    
    public p10p5Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P10P5' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FLSD' INTEGER," + // 1: flsd
                "'FEL' INTEGER," + // 2: fel
                "'FIP' INTEGER," + // 3: fip
                "'RAPA' INTEGER," + // 4: rapa
                "'DBLE' INTEGER," + // 5: dble
                "'RPC' INTEGER," + // 6: rpc
                "'ORIGEN' INTEGER," + // 7: origen
                "'OBSER' TEXT," + // 8: obser
                "'ID_FORMULARIO' INTEGER);"); // 9: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P10P5'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p10p5 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer flsd = entity.getFlsd();
        if (flsd != null) {
            stmt.bindLong(2, flsd);
        }
 
        Integer fel = entity.getFel();
        if (fel != null) {
            stmt.bindLong(3, fel);
        }
 
        Integer fip = entity.getFip();
        if (fip != null) {
            stmt.bindLong(4, fip);
        }
 
        Integer rapa = entity.getRapa();
        if (rapa != null) {
            stmt.bindLong(5, rapa);
        }
 
        Integer dble = entity.getDble();
        if (dble != null) {
            stmt.bindLong(6, dble);
        }
 
        Integer rpc = entity.getRpc();
        if (rpc != null) {
            stmt.bindLong(7, rpc);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(8, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(9, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(10, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p10p5 readEntity(Cursor cursor, int offset) {
        p10p5 entity = new p10p5( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // flsd
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // fel
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // fip
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // rapa
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // dble
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // rpc
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // origen
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // obser
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p10p5 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFlsd(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setFel(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setFip(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setRapa(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setDble(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setRpc(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setOrigen(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setObser(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setId_formulario(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p10p5 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p10p5 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
