package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P1P10.
 */
public class p1p10 {

    private Long id;
    private Integer spem;
    private Integer sef;
    private Integer set;
    private Integer poi;
    private Integer rtra;
    private Integer pad;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p1p10() {
    }

    public p1p10(Long id) {
        this.id = id;
    }

    public p1p10(Long id, Integer spem, Integer sef, Integer set, Integer poi, Integer rtra, Integer pad, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.spem = spem;
        this.sef = sef;
        this.set = set;
        this.poi = poi;
        this.rtra = rtra;
        this.pad = pad;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSpem() {
        return spem;
    }

    public void setSpem(Integer spem) {
        this.spem = spem;
    }

    public Integer getSef() {
        return sef;
    }

    public void setSef(Integer sef) {
        this.sef = sef;
    }

    public Integer getSet() {
        return set;
    }

    public void setSet(Integer set) {
        this.set = set;
    }

    public Integer getPoi() {
        return poi;
    }

    public void setPoi(Integer poi) {
        this.poi = poi;
    }

    public Integer getRtra() {
        return rtra;
    }

    public void setRtra(Integer rtra) {
        this.rtra = rtra;
    }

    public Integer getPad() {
        return pad;
    }

    public void setPad(Integer pad) {
        this.pad = pad;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
