package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P1P6.
 */
public class p1p6 {

    private Long id;
    private Integer epino;
    private Integer erlv;
    private Integer erac;
    private Integer eipi;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p1p6() {
    }

    public p1p6(Long id) {
        this.id = id;
    }

    public p1p6(Long id, Integer epino, Integer erlv, Integer erac, Integer eipi, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.epino = epino;
        this.erlv = erlv;
        this.erac = erac;
        this.eipi = eipi;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getEpino() {
        return epino;
    }

    public void setEpino(Integer epino) {
        this.epino = epino;
    }

    public Integer getErlv() {
        return erlv;
    }

    public void setErlv(Integer erlv) {
        this.erlv = erlv;
    }

    public Integer getErac() {
        return erac;
    }

    public void setErac(Integer erac) {
        this.erac = erac;
    }

    public Integer getEipi() {
        return eipi;
    }

    public void setEipi(Integer eipi) {
        this.eipi = eipi;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
