package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P1P7.
 */
public class p1p7 {

    private Long id;
    private Integer cppr;
    private Integer rdr;
    private Integer iap;
    private Integer pmc;
    private Integer seg;
    private Integer med;
    private Integer ana;
    private Integer trab;
    private Integer grup;
    private Integer oper;
    private Integer aco;
    private Integer mdea;
    private Integer mdam;
    private Integer apam;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p1p7() {
    }

    public p1p7(Long id) {
        this.id = id;
    }

    public p1p7(Long id, Integer cppr, Integer rdr, Integer iap, Integer pmc, Integer seg, Integer med, Integer ana, Integer trab, Integer grup, Integer oper, Integer aco, Integer mdea, Integer mdam, Integer apam, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.cppr = cppr;
        this.rdr = rdr;
        this.iap = iap;
        this.pmc = pmc;
        this.seg = seg;
        this.med = med;
        this.ana = ana;
        this.trab = trab;
        this.grup = grup;
        this.oper = oper;
        this.aco = aco;
        this.mdea = mdea;
        this.mdam = mdam;
        this.apam = apam;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCppr() {
        return cppr;
    }

    public void setCppr(Integer cppr) {
        this.cppr = cppr;
    }

    public Integer getRdr() {
        return rdr;
    }

    public void setRdr(Integer rdr) {
        this.rdr = rdr;
    }

    public Integer getIap() {
        return iap;
    }

    public void setIap(Integer iap) {
        this.iap = iap;
    }

    public Integer getPmc() {
        return pmc;
    }

    public void setPmc(Integer pmc) {
        this.pmc = pmc;
    }

    public Integer getSeg() {
        return seg;
    }

    public void setSeg(Integer seg) {
        this.seg = seg;
    }

    public Integer getMed() {
        return med;
    }

    public void setMed(Integer med) {
        this.med = med;
    }

    public Integer getAna() {
        return ana;
    }

    public void setAna(Integer ana) {
        this.ana = ana;
    }

    public Integer getTrab() {
        return trab;
    }

    public void setTrab(Integer trab) {
        this.trab = trab;
    }

    public Integer getGrup() {
        return grup;
    }

    public void setGrup(Integer grup) {
        this.grup = grup;
    }

    public Integer getOper() {
        return oper;
    }

    public void setOper(Integer oper) {
        this.oper = oper;
    }

    public Integer getAco() {
        return aco;
    }

    public void setAco(Integer aco) {
        this.aco = aco;
    }

    public Integer getMdea() {
        return mdea;
    }

    public void setMdea(Integer mdea) {
        this.mdea = mdea;
    }

    public Integer getMdam() {
        return mdam;
    }

    public void setMdam(Integer mdam) {
        this.mdam = mdam;
    }

    public Integer getApam() {
        return apam;
    }

    public void setApam(Integer apam) {
        this.apam = apam;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
