package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P1P9.
 */
public class p1p9 {

    private Long id;
    private Integer pcsg;
    private Integer pdc;
    private Integer pde;
    private Integer rda;
    private Integer rdt;
    private Integer rdi;
    private Integer actr;
    private Integer norm;
    private Integer pdt;
    private Integer tdl;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p1p9() {
    }

    public p1p9(Long id) {
        this.id = id;
    }

    public p1p9(Long id, Integer pcsg, Integer pdc, Integer pde, Integer rda, Integer rdt, Integer rdi, Integer actr, Integer norm, Integer pdt, Integer tdl, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.pcsg = pcsg;
        this.pdc = pdc;
        this.pde = pde;
        this.rda = rda;
        this.rdt = rdt;
        this.rdi = rdi;
        this.actr = actr;
        this.norm = norm;
        this.pdt = pdt;
        this.tdl = tdl;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPcsg() {
        return pcsg;
    }

    public void setPcsg(Integer pcsg) {
        this.pcsg = pcsg;
    }

    public Integer getPdc() {
        return pdc;
    }

    public void setPdc(Integer pdc) {
        this.pdc = pdc;
    }

    public Integer getPde() {
        return pde;
    }

    public void setPde(Integer pde) {
        this.pde = pde;
    }

    public Integer getRda() {
        return rda;
    }

    public void setRda(Integer rda) {
        this.rda = rda;
    }

    public Integer getRdt() {
        return rdt;
    }

    public void setRdt(Integer rdt) {
        this.rdt = rdt;
    }

    public Integer getRdi() {
        return rdi;
    }

    public void setRdi(Integer rdi) {
        this.rdi = rdi;
    }

    public Integer getActr() {
        return actr;
    }

    public void setActr(Integer actr) {
        this.actr = actr;
    }

    public Integer getNorm() {
        return norm;
    }

    public void setNorm(Integer norm) {
        this.norm = norm;
    }

    public Integer getPdt() {
        return pdt;
    }

    public void setPdt(Integer pdt) {
        this.pdt = pdt;
    }

    public Integer getTdl() {
        return tdl;
    }

    public void setTdl(Integer tdl) {
        this.tdl = tdl;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
