package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P2P1.
 */
public class p2p1 {

    private Long id;
    private Integer eco_pro_rec;
    private Integer eco_nat;
    private Integer prog_con;
    private Integer iden_eco;
    private Integer pro_eco;
    private Integer rec_eco;
    private Integer prog_inc_eco;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p2p1() {
    }

    public p2p1(Long id) {
        this.id = id;
    }

    public p2p1(Long id, Integer eco_pro_rec, Integer eco_nat, Integer prog_con, Integer iden_eco, Integer pro_eco, Integer rec_eco, Integer prog_inc_eco, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.eco_pro_rec = eco_pro_rec;
        this.eco_nat = eco_nat;
        this.prog_con = prog_con;
        this.iden_eco = iden_eco;
        this.pro_eco = pro_eco;
        this.rec_eco = rec_eco;
        this.prog_inc_eco = prog_inc_eco;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getEco_pro_rec() {
        return eco_pro_rec;
    }

    public void setEco_pro_rec(Integer eco_pro_rec) {
        this.eco_pro_rec = eco_pro_rec;
    }

    public Integer getEco_nat() {
        return eco_nat;
    }

    public void setEco_nat(Integer eco_nat) {
        this.eco_nat = eco_nat;
    }

    public Integer getProg_con() {
        return prog_con;
    }

    public void setProg_con(Integer prog_con) {
        this.prog_con = prog_con;
    }

    public Integer getIden_eco() {
        return iden_eco;
    }

    public void setIden_eco(Integer iden_eco) {
        this.iden_eco = iden_eco;
    }

    public Integer getPro_eco() {
        return pro_eco;
    }

    public void setPro_eco(Integer pro_eco) {
        this.pro_eco = pro_eco;
    }

    public Integer getRec_eco() {
        return rec_eco;
    }

    public void setRec_eco(Integer rec_eco) {
        this.rec_eco = rec_eco;
    }

    public Integer getProg_inc_eco() {
        return prog_inc_eco;
    }

    public void setProg_inc_eco(Integer prog_inc_eco) {
        this.prog_inc_eco = prog_inc_eco;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
