package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P2P3.
 */
public class p2p3 {

    private Long id;
    private Integer apnuc;
    private Integer pnz;
    private Integer rvs;
    private Integer azm;
    private Integer spn;
    private Integer rfp;
    private Integer pnr;
    private Integer dmi;
    private Integer dcs;
    private Integer arec;
    private Integer rnsc;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p2p3() {
    }

    public p2p3(Long id) {
        this.id = id;
    }

    public p2p3(Long id, Integer apnuc, Integer pnz, Integer rvs, Integer azm, Integer spn, Integer rfp, Integer pnr, Integer dmi, Integer dcs, Integer arec, Integer rnsc, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.apnuc = apnuc;
        this.pnz = pnz;
        this.rvs = rvs;
        this.azm = azm;
        this.spn = spn;
        this.rfp = rfp;
        this.pnr = pnr;
        this.dmi = dmi;
        this.dcs = dcs;
        this.arec = arec;
        this.rnsc = rnsc;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getApnuc() {
        return apnuc;
    }

    public void setApnuc(Integer apnuc) {
        this.apnuc = apnuc;
    }

    public Integer getPnz() {
        return pnz;
    }

    public void setPnz(Integer pnz) {
        this.pnz = pnz;
    }

    public Integer getRvs() {
        return rvs;
    }

    public void setRvs(Integer rvs) {
        this.rvs = rvs;
    }

    public Integer getAzm() {
        return azm;
    }

    public void setAzm(Integer azm) {
        this.azm = azm;
    }

    public Integer getSpn() {
        return spn;
    }

    public void setSpn(Integer spn) {
        this.spn = spn;
    }

    public Integer getRfp() {
        return rfp;
    }

    public void setRfp(Integer rfp) {
        this.rfp = rfp;
    }

    public Integer getPnr() {
        return pnr;
    }

    public void setPnr(Integer pnr) {
        this.pnr = pnr;
    }

    public Integer getDmi() {
        return dmi;
    }

    public void setDmi(Integer dmi) {
        this.dmi = dmi;
    }

    public Integer getDcs() {
        return dcs;
    }

    public void setDcs(Integer dcs) {
        this.dcs = dcs;
    }

    public Integer getArec() {
        return arec;
    }

    public void setArec(Integer arec) {
        this.arec = arec;
    }

    public Integer getRnsc() {
        return rnsc;
    }

    public void setRnsc(Integer rnsc) {
        this.rnsc = rnsc;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
