package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p2p4;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P2P4.
*/
public class p2p4Dao extends AbstractDao<p2p4, Long> {

    public static final String TABLENAME = "P2P4";

    /**
     * Properties of entity p2p4.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Npep = new Property(1, Integer.class, "npep", false, "NPEP");
        public final static Property Ntpm = new Property(2, Integer.class, "ntpm", false, "NTPM");
        public final static Property Cpms = new Property(3, Integer.class, "cpms", false, "CPMS");
        public final static Property Cpdl = new Property(4, Integer.class, "cpdl", false, "CPDL");
        public final static Property Nsep = new Property(5, Integer.class, "nsep", false, "NSEP");
        public final static Property Origen = new Property(6, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(7, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(8, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public p2p4Dao(DaoConfig config) {
        super(config);
    }
    
    public p2p4Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P2P4' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NPEP' INTEGER," + // 1: npep
                "'NTPM' INTEGER," + // 2: ntpm
                "'CPMS' INTEGER," + // 3: cpms
                "'CPDL' INTEGER," + // 4: cpdl
                "'NSEP' INTEGER," + // 5: nsep
                "'ORIGEN' INTEGER," + // 6: origen
                "'OBSER' TEXT," + // 7: obser
                "'ID_FORMULARIO' INTEGER);"); // 8: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P2P4'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p2p4 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer npep = entity.getNpep();
        if (npep != null) {
            stmt.bindLong(2, npep);
        }
 
        Integer ntpm = entity.getNtpm();
        if (ntpm != null) {
            stmt.bindLong(3, ntpm);
        }
 
        Integer cpms = entity.getCpms();
        if (cpms != null) {
            stmt.bindLong(4, cpms);
        }
 
        Integer cpdl = entity.getCpdl();
        if (cpdl != null) {
            stmt.bindLong(5, cpdl);
        }
 
        Integer nsep = entity.getNsep();
        if (nsep != null) {
            stmt.bindLong(6, nsep);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(7, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(8, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(9, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p2p4 readEntity(Cursor cursor, int offset) {
        p2p4 entity = new p2p4( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // npep
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // ntpm
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // cpms
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // cpdl
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // nsep
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // origen
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // obser
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p2p4 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNpep(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setNtpm(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCpms(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setCpdl(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setNsep(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOrigen(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setObser(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setId_formulario(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p2p4 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p2p4 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
