package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P2P4.
 */
public class p2p4 {

    private Long id;
    private Integer fndsn;
    private Integer eav;
    private Integer nede;
    private Integer ndedc;
    private Integer nden;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p2p4() {
    }

    public p2p4(Long id) {
        this.id = id;
    }

    public p2p4(Long id, Integer fndsn, Integer eav, Integer nede, Integer ndedc, Integer nden, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.fndsn = fndsn;
        this.eav = eav;
        this.nede = nede;
        this.ndedc = ndedc;
        this.nden = nden;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFndsn() {
        return fndsn;
    }

    public void setFndsn(Integer fndsn) {
        this.fndsn = fndsn;
    }

    public Integer getEav() {
        return eav;
    }

    public void setEav(Integer eav) {
        this.eav = eav;
    }

    public Integer getNede() {
        return nede;
    }

    public void setNede(Integer nede) {
        this.nede = nede;
    }

    public Integer getNdedc() {
        return ndedc;
    }

    public void setNdedc(Integer ndedc) {
        this.ndedc = ndedc;
    }

    public Integer getNden() {
        return nden;
    }

    public void setNden(Integer nden) {
        this.nden = nden;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
