package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P2P4.
 */
public class p2p4 {

    private Long id;
    private Integer nsep;
    private Integer ntpm;
    private Integer cpms;
    private Integer cpdl;
    private Integer npep;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p2p4() {
    }

    public p2p4(Long id) {
        this.id = id;
    }

    public p2p4(Long id, Integer nsep, Integer ntpm, Integer cpms, Integer cpdl, Integer npep, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.nsep = nsep;
        this.ntpm = ntpm;
        this.cpms = cpms;
        this.cpdl = cpdl;
        this.npep = npep;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNsep() {
        return nsep;
    }

    public void setNsep(Integer nsep) {
        this.nsep = nsep;
    }

    public Integer getNtpm() {
        return ntpm;
    }

    public void setNtpm(Integer ntpm) {
        this.ntpm = ntpm;
    }

    public Integer getCpms() {
        return cpms;
    }

    public void setCpms(Integer cpms) {
        this.cpms = cpms;
    }

    public Integer getCpdl() {
        return cpdl;
    }

    public void setCpdl(Integer cpdl) {
        this.cpdl = cpdl;
    }

    public Integer getNpep() {
        return npep;
    }

    public void setNpep(Integer npep) {
        this.npep = npep;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
