package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P2P7.
 */
public class p2p7 {

    private Long id;
    private Integer nhah;
    private Integer buvn;
    private Integer cah;
    private Integer apc;
    private Integer rdpyh;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p2p7() {
    }

    public p2p7(Long id) {
        this.id = id;
    }

    public p2p7(Long id, Integer nhah, Integer buvn, Integer cah, Integer apc, Integer rdpyh, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.nhah = nhah;
        this.buvn = buvn;
        this.cah = cah;
        this.apc = apc;
        this.rdpyh = rdpyh;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNhah() {
        return nhah;
    }

    public void setNhah(Integer nhah) {
        this.nhah = nhah;
    }

    public Integer getBuvn() {
        return buvn;
    }

    public void setBuvn(Integer buvn) {
        this.buvn = buvn;
    }

    public Integer getCah() {
        return cah;
    }

    public void setCah(Integer cah) {
        this.cah = cah;
    }

    public Integer getApc() {
        return apc;
    }

    public void setApc(Integer apc) {
        this.apc = apc;
    }

    public Integer getRdpyh() {
        return rdpyh;
    }

    public void setRdpyh(Integer rdpyh) {
        this.rdpyh = rdpyh;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
