package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p2p7;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P2P7.
*/
public class p2p7Dao extends AbstractDao<p2p7, Long> {

    public static final String TABLENAME = "P2P7";

    /**
     * Properties of entity p2p7.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nhah = new Property(1, Integer.class, "nhah", false, "NHAH");
        public final static Property Buvn = new Property(2, Integer.class, "buvn", false, "BUVN");
        public final static Property Cah = new Property(3, Integer.class, "cah", false, "CAH");
        public final static Property Apc = new Property(4, Integer.class, "apc", false, "APC");
        public final static Property Rdpyh = new Property(5, Integer.class, "rdpyh", false, "RDPYH");
        public final static Property Origen = new Property(6, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(7, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(8, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p2p7Dao(DaoConfig config) {
        super(config);
    }
    
    public p2p7Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P2P7' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NHAH' INTEGER," + // 1: nhah
                "'BUVN' INTEGER," + // 2: buvn
                "'CAH' INTEGER," + // 3: cah
                "'APC' INTEGER," + // 4: apc
                "'RDPYH' INTEGER," + // 5: rdpyh
                "'ORIGEN' INTEGER," + // 6: origen
                "'ID_FORMULARIO' INTEGER," + // 7: id_formulario
                "'OBSERVACIONES' TEXT);"); // 8: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P2P7'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p2p7 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer nhah = entity.getNhah();
        if (nhah != null) {
            stmt.bindLong(2, nhah);
        }
 
        Integer buvn = entity.getBuvn();
        if (buvn != null) {
            stmt.bindLong(3, buvn);
        }
 
        Integer cah = entity.getCah();
        if (cah != null) {
            stmt.bindLong(4, cah);
        }
 
        Integer apc = entity.getApc();
        if (apc != null) {
            stmt.bindLong(5, apc);
        }
 
        Integer rdpyh = entity.getRdpyh();
        if (rdpyh != null) {
            stmt.bindLong(6, rdpyh);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(7, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(8, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(9, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p2p7 readEntity(Cursor cursor, int offset) {
        p2p7 entity = new p2p7( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // nhah
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // buvn
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // cah
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // apc
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // rdpyh
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // origen
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // id_formulario
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p2p7 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNhah(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setBuvn(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCah(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setApc(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setRdpyh(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOrigen(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setId_formulario(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setObservaciones(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p2p7 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p2p7 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
