package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P2P8.
 */
public class p2p8 {

    private Long id;
    private Integer ncaf;
    private String denp;
    private String dea;
    private String neh;
    private String adre;
    private Integer admh;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p2p8() {
    }

    public p2p8(Long id) {
        this.id = id;
    }

    public p2p8(Long id, Integer ncaf, String denp, String dea, String neh, String adre, Integer admh, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.ncaf = ncaf;
        this.denp = denp;
        this.dea = dea;
        this.neh = neh;
        this.adre = adre;
        this.admh = admh;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNcaf() {
        return ncaf;
    }

    public void setNcaf(Integer ncaf) {
        this.ncaf = ncaf;
    }

    public String getDenp() {
        return denp;
    }

    public void setDenp(String denp) {
        this.denp = denp;
    }

    public String getDea() {
        return dea;
    }

    public void setDea(String dea) {
        this.dea = dea;
    }

    public String getNeh() {
        return neh;
    }

    public void setNeh(String neh) {
        this.neh = neh;
    }

    public String getAdre() {
        return adre;
    }

    public void setAdre(String adre) {
        this.adre = adre;
    }

    public Integer getAdmh() {
        return admh;
    }

    public void setAdmh(Integer admh) {
        this.admh = admh;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
