package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P3P1.
 */
public class p3p1 {

    private Long id;
    private Integer cmivs;
    private Integer ivs;
    private Integer idh;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p3p1() {
    }

    public p3p1(Long id) {
        this.id = id;
    }

    public p3p1(Long id, Integer cmivs, Integer ivs, Integer idh, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.cmivs = cmivs;
        this.ivs = ivs;
        this.idh = idh;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCmivs() {
        return cmivs;
    }

    public void setCmivs(Integer cmivs) {
        this.cmivs = cmivs;
    }

    public Integer getIvs() {
        return ivs;
    }

    public void setIvs(Integer ivs) {
        this.ivs = ivs;
    }

    public Integer getIdh() {
        return idh;
    }

    public void setIdh(Integer idh) {
        this.idh = idh;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
