package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P4P3.
 */
public class p4p3 {

    private Long id;
    private Integer fntr;
    private Integer mpma;
    private Integer dnpsa;
    private Integer dcau;
    private Integer sred;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p4p3() {
    }

    public p4p3(Long id) {
        this.id = id;
    }

    public p4p3(Long id, Integer fntr, Integer mpma, Integer dnpsa, Integer dcau, Integer sred, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.fntr = fntr;
        this.mpma = mpma;
        this.dnpsa = dnpsa;
        this.dcau = dcau;
        this.sred = sred;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFntr() {
        return fntr;
    }

    public void setFntr(Integer fntr) {
        this.fntr = fntr;
    }

    public Integer getMpma() {
        return mpma;
    }

    public void setMpma(Integer mpma) {
        this.mpma = mpma;
    }

    public Integer getDnpsa() {
        return dnpsa;
    }

    public void setDnpsa(Integer dnpsa) {
        this.dnpsa = dnpsa;
    }

    public Integer getDcau() {
        return dcau;
    }

    public void setDcau(Integer dcau) {
        this.dcau = dcau;
    }

    public Integer getSred() {
        return sred;
    }

    public void setSred(Integer sred) {
        this.sred = sred;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
