package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p4p3;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P4P3.
*/
public class p4p3Dao extends AbstractDao<p4p3, Long> {

    public static final String TABLENAME = "P4P3";

    /**
     * Properties of entity p4p3.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fntr = new Property(1, Integer.class, "fntr", false, "FNTR");
        public final static Property Mpma = new Property(2, Integer.class, "mpma", false, "MPMA");
        public final static Property Dnpsa = new Property(3, Integer.class, "dnpsa", false, "DNPSA");
        public final static Property Dcau = new Property(4, Integer.class, "dcau", false, "DCAU");
        public final static Property Sred = new Property(5, Integer.class, "sred", false, "SRED");
        public final static Property Origen = new Property(6, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(7, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(8, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p4p3Dao(DaoConfig config) {
        super(config);
    }
    
    public p4p3Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P4P3' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FNTR' INTEGER," + // 1: fntr
                "'MPMA' INTEGER," + // 2: mpma
                "'DNPSA' INTEGER," + // 3: dnpsa
                "'DCAU' INTEGER," + // 4: dcau
                "'SRED' INTEGER," + // 5: sred
                "'ORIGEN' INTEGER," + // 6: origen
                "'ID_FORMULARIO' INTEGER," + // 7: id_formulario
                "'OBSERVACIONES' TEXT);"); // 8: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P4P3'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p4p3 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer fntr = entity.getFntr();
        if (fntr != null) {
            stmt.bindLong(2, fntr);
        }
 
        Integer mpma = entity.getMpma();
        if (mpma != null) {
            stmt.bindLong(3, mpma);
        }
 
        Integer dnpsa = entity.getDnpsa();
        if (dnpsa != null) {
            stmt.bindLong(4, dnpsa);
        }
 
        Integer dcau = entity.getDcau();
        if (dcau != null) {
            stmt.bindLong(5, dcau);
        }
 
        Integer sred = entity.getSred();
        if (sred != null) {
            stmt.bindLong(6, sred);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(7, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(8, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(9, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p4p3 readEntity(Cursor cursor, int offset) {
        p4p3 entity = new p4p3( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // fntr
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // mpma
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // dnpsa
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // dcau
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // sred
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // origen
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // id_formulario
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p4p3 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFntr(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setMpma(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setDnpsa(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setDcau(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setSred(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOrigen(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setId_formulario(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setObservaciones(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p4p3 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p4p3 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
