package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p4p5;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P4P5.
*/
public class p4p5Dao extends AbstractDao<p4p5, Long> {

    public static final String TABLENAME = "P4P5";

    /**
     * Properties of entity p4p5.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nsasa = new Property(1, Integer.class, "nsasa", false, "NSASA");
        public final static Property Avcp = new Property(2, Integer.class, "avcp", false, "AVCP");
        public final static Property Nsarc = new Property(3, Integer.class, "nsarc", false, "NSARC");
        public final static Property Origen = new Property(4, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(5, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(6, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p4p5Dao(DaoConfig config) {
        super(config);
    }
    
    public p4p5Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P4P5' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NSASA' INTEGER," + // 1: nsasa
                "'AVCP' INTEGER," + // 2: avcp
                "'NSARC' INTEGER," + // 3: nsarc
                "'ORIGEN' INTEGER," + // 4: origen
                "'ID_FORMULARIO' INTEGER," + // 5: id_formulario
                "'OBSERVACIONES' TEXT);"); // 6: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P4P5'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p4p5 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer nsasa = entity.getNsasa();
        if (nsasa != null) {
            stmt.bindLong(2, nsasa);
        }
 
        Integer avcp = entity.getAvcp();
        if (avcp != null) {
            stmt.bindLong(3, avcp);
        }
 
        Integer nsarc = entity.getNsarc();
        if (nsarc != null) {
            stmt.bindLong(4, nsarc);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(5, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(6, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(7, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p4p5 readEntity(Cursor cursor, int offset) {
        p4p5 entity = new p4p5( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // nsasa
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // avcp
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // nsarc
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // origen
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // id_formulario
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p4p5 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNsasa(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setAvcp(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setNsarc(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setOrigen(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setId_formulario(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setObservaciones(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p4p5 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p4p5 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
