package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P4P5.
 */
public class p4p5 {

    private Long id;
    private Integer nsasa;
    private Integer avcp;
    private Integer nsarc;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p4p5() {
    }

    public p4p5(Long id) {
        this.id = id;
    }

    public p4p5(Long id, Integer nsasa, Integer avcp, Integer nsarc, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.nsasa = nsasa;
        this.avcp = avcp;
        this.nsarc = nsarc;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNsasa() {
        return nsasa;
    }

    public void setNsasa(Integer nsasa) {
        this.nsasa = nsasa;
    }

    public Integer getAvcp() {
        return avcp;
    }

    public void setAvcp(Integer avcp) {
        this.avcp = avcp;
    }

    public Integer getNsarc() {
        return nsarc;
    }

    public void setNsarc(Integer nsarc) {
        this.nsarc = nsarc;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
