package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p4p6;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P4P6.
*/
public class p4p6Dao extends AbstractDao<p4p6, Long> {

    public static final String TABLENAME = "P4P6";

    /**
     * Properties of entity p4p6.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nvara = new Property(1, Integer.class, "nvara", false, "NVARA");
        public final static Property Laba = new Property(2, Integer.class, "laba", false, "LABA");
        public final static Property Proma = new Property(3, Integer.class, "proma", false, "PROMA");
        public final static Property Procr = new Property(4, Integer.class, "procr", false, "PROCR");
        public final static Property Origen = new Property(5, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(6, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(7, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p4p6Dao(DaoConfig config) {
        super(config);
    }
    
    public p4p6Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P4P6' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NVARA' INTEGER," + // 1: nvara
                "'LABA' INTEGER," + // 2: laba
                "'PROMA' INTEGER," + // 3: proma
                "'PROCR' INTEGER," + // 4: procr
                "'ORIGEN' INTEGER," + // 5: origen
                "'ID_FORMULARIO' INTEGER," + // 6: id_formulario
                "'OBSERVACIONES' TEXT);"); // 7: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P4P6'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p4p6 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer nvara = entity.getNvara();
        if (nvara != null) {
            stmt.bindLong(2, nvara);
        }
 
        Integer laba = entity.getLaba();
        if (laba != null) {
            stmt.bindLong(3, laba);
        }
 
        Integer proma = entity.getProma();
        if (proma != null) {
            stmt.bindLong(4, proma);
        }
 
        Integer procr = entity.getProcr();
        if (procr != null) {
            stmt.bindLong(5, procr);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(6, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(7, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(8, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p4p6 readEntity(Cursor cursor, int offset) {
        p4p6 entity = new p4p6( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // nvara
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // laba
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // proma
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // procr
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // origen
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // id_formulario
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p4p6 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNvara(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setLaba(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setProma(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setProcr(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOrigen(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setId_formulario(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setObservaciones(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p4p6 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p4p6 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
