package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P4P7.
 */
public class p4p7 {

    private Long id;
    private Integer fnpd;
    private Integer nsda;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p4p7() {
    }

    public p4p7(Long id) {
        this.id = id;
    }

    public p4p7(Long id, Integer fnpd, Integer nsda, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.fnpd = fnpd;
        this.nsda = nsda;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFnpd() {
        return fnpd;
    }

    public void setFnpd(Integer fnpd) {
        this.fnpd = fnpd;
    }

    public Integer getNsda() {
        return nsda;
    }

    public void setNsda(Integer nsda) {
        this.nsda = nsda;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
