package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P4P9.
 */
public class p4p9 {

    private Long id;
    private Integer fcpr;
    private Integer pmas;
    private Integer frec;
    private Integer anar;
    private Integer pmue;
    private Integer amdc;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p4p9() {
    }

    public p4p9(Long id) {
        this.id = id;
    }

    public p4p9(Long id, Integer fcpr, Integer pmas, Integer frec, Integer anar, Integer pmue, Integer amdc, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.fcpr = fcpr;
        this.pmas = pmas;
        this.frec = frec;
        this.anar = anar;
        this.pmue = pmue;
        this.amdc = amdc;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFcpr() {
        return fcpr;
    }

    public void setFcpr(Integer fcpr) {
        this.fcpr = fcpr;
    }

    public Integer getPmas() {
        return pmas;
    }

    public void setPmas(Integer pmas) {
        this.pmas = pmas;
    }

    public Integer getFrec() {
        return frec;
    }

    public void setFrec(Integer frec) {
        this.frec = frec;
    }

    public Integer getAnar() {
        return anar;
    }

    public void setAnar(Integer anar) {
        this.anar = anar;
    }

    public Integer getPmue() {
        return pmue;
    }

    public void setPmue(Integer pmue) {
        this.pmue = pmue;
    }

    public Integer getAmdc() {
        return amdc;
    }

    public void setAmdc(Integer amdc) {
        this.amdc = amdc;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
