package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P5P12.
 */
public class p5p12 {

    private Long id;
    private Integer armf;
    private Integer pgd;
    private Integer numt;
    private Integer tdol;
    private Integer fprt;
    private Integer ideo;
    private Integer rel;
    private Integer soc;
    private Integer pol;
    private Integer cul;
    private String de;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p5p12() {
    }

    public p5p12(Long id) {
        this.id = id;
    }

    public p5p12(Long id, Integer armf, Integer pgd, Integer numt, Integer tdol, Integer fprt, Integer ideo, Integer rel, Integer soc, Integer pol, Integer cul, String de, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.armf = armf;
        this.pgd = pgd;
        this.numt = numt;
        this.tdol = tdol;
        this.fprt = fprt;
        this.ideo = ideo;
        this.rel = rel;
        this.soc = soc;
        this.pol = pol;
        this.cul = cul;
        this.de = de;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArmf() {
        return armf;
    }

    public void setArmf(Integer armf) {
        this.armf = armf;
    }

    public Integer getPgd() {
        return pgd;
    }

    public void setPgd(Integer pgd) {
        this.pgd = pgd;
    }

    public Integer getNumt() {
        return numt;
    }

    public void setNumt(Integer numt) {
        this.numt = numt;
    }

    public Integer getTdol() {
        return tdol;
    }

    public void setTdol(Integer tdol) {
        this.tdol = tdol;
    }

    public Integer getFprt() {
        return fprt;
    }

    public void setFprt(Integer fprt) {
        this.fprt = fprt;
    }

    public Integer getIdeo() {
        return ideo;
    }

    public void setIdeo(Integer ideo) {
        this.ideo = ideo;
    }

    public Integer getRel() {
        return rel;
    }

    public void setRel(Integer rel) {
        this.rel = rel;
    }

    public Integer getSoc() {
        return soc;
    }

    public void setSoc(Integer soc) {
        this.soc = soc;
    }

    public Integer getPol() {
        return pol;
    }

    public void setPol(Integer pol) {
        this.pol = pol;
    }

    public Integer getCul() {
        return cul;
    }

    public void setCul(Integer cul) {
        this.cul = cul;
    }

    public String getDe() {
        return de;
    }

    public void setDe(String de) {
        this.de = de;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
