package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p5p11;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P5P11.
*/
public class p5p11Dao extends AbstractDao<p5p11, Long> {

    public static final String TABLENAME = "P5P11";

    /**
     * Properties of entity p5p11.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Armf = new Property(1, Integer.class, "armf", false, "ARMF");
        public final static Property Ftrt = new Property(2, Integer.class, "ftrt", false, "FTRT");
        public final static Property Snat = new Property(3, Integer.class, "snat", false, "SNAT");
        public final static Property Mfmt = new Property(4, Integer.class, "mfmt", false, "MFMT");
        public final static Property Origen = new Property(5, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(6, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(7, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p5p11Dao(DaoConfig config) {
        super(config);
    }
    
    public p5p11Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P5P11' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ARMF' INTEGER," + // 1: armf
                "'FTRT' INTEGER," + // 2: ftrt
                "'SNAT' INTEGER," + // 3: snat
                "'MFMT' INTEGER," + // 4: mfmt
                "'ORIGEN' INTEGER," + // 5: origen
                "'ID_FORMULARIO' INTEGER," + // 6: id_formulario
                "'OBSERVACIONES' TEXT);"); // 7: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P5P11'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p5p11 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer armf = entity.getArmf();
        if (armf != null) {
            stmt.bindLong(2, armf);
        }
 
        Integer ftrt = entity.getFtrt();
        if (ftrt != null) {
            stmt.bindLong(3, ftrt);
        }
 
        Integer snat = entity.getSnat();
        if (snat != null) {
            stmt.bindLong(4, snat);
        }
 
        Integer mfmt = entity.getMfmt();
        if (mfmt != null) {
            stmt.bindLong(5, mfmt);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(6, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(7, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(8, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p5p11 readEntity(Cursor cursor, int offset) {
        p5p11 entity = new p5p11( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // armf
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // ftrt
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // snat
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // mfmt
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // origen
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // id_formulario
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p5p11 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setArmf(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setFtrt(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setSnat(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setMfmt(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOrigen(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setId_formulario(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setObservaciones(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p5p11 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p5p11 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
