package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P5P14.
 */
public class p5p14 {

    private Long id;
    private Integer fnav;
    private Integer hig;
    private Integer segh;
    private Integer sal;
    private Integer vfap;
    private Integer ttar;
    private Integer sbdn;
    private Integer idta;
    private Integer memc;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p5p14() {
    }

    public p5p14(Long id) {
        this.id = id;
    }

    public p5p14(Long id, Integer fnav, Integer hig, Integer segh, Integer sal, Integer vfap, Integer ttar, Integer sbdn, Integer idta, Integer memc, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.fnav = fnav;
        this.hig = hig;
        this.segh = segh;
        this.sal = sal;
        this.vfap = vfap;
        this.ttar = ttar;
        this.sbdn = sbdn;
        this.idta = idta;
        this.memc = memc;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFnav() {
        return fnav;
    }

    public void setFnav(Integer fnav) {
        this.fnav = fnav;
    }

    public Integer getHig() {
        return hig;
    }

    public void setHig(Integer hig) {
        this.hig = hig;
    }

    public Integer getSegh() {
        return segh;
    }

    public void setSegh(Integer segh) {
        this.segh = segh;
    }

    public Integer getSal() {
        return sal;
    }

    public void setSal(Integer sal) {
        this.sal = sal;
    }

    public Integer getVfap() {
        return vfap;
    }

    public void setVfap(Integer vfap) {
        this.vfap = vfap;
    }

    public Integer getTtar() {
        return ttar;
    }

    public void setTtar(Integer ttar) {
        this.ttar = ttar;
    }

    public Integer getSbdn() {
        return sbdn;
    }

    public void setSbdn(Integer sbdn) {
        this.sbdn = sbdn;
    }

    public Integer getIdta() {
        return idta;
    }

    public void setIdta(Integer idta) {
        this.idta = idta;
    }

    public Integer getMemc() {
        return memc;
    }

    public void setMemc(Integer memc) {
        this.memc = memc;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
