package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P5P1.
 */
public class p5p1 {

    private Long id;
    private Integer armhf;
    private Integer polso;
    private Integer apad;
    private Integer psdcf;
    private Integer div;
    private Integer cpf;
    private Integer dpe;
    private Integer comu;
    private Integer rdtya;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p5p1() {
    }

    public p5p1(Long id) {
        this.id = id;
    }

    public p5p1(Long id, Integer armhf, Integer polso, Integer apad, Integer psdcf, Integer div, Integer cpf, Integer dpe, Integer comu, Integer rdtya, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.armhf = armhf;
        this.polso = polso;
        this.apad = apad;
        this.psdcf = psdcf;
        this.div = div;
        this.cpf = cpf;
        this.dpe = dpe;
        this.comu = comu;
        this.rdtya = rdtya;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArmhf() {
        return armhf;
    }

    public void setArmhf(Integer armhf) {
        this.armhf = armhf;
    }

    public Integer getPolso() {
        return polso;
    }

    public void setPolso(Integer polso) {
        this.polso = polso;
    }

    public Integer getApad() {
        return apad;
    }

    public void setApad(Integer apad) {
        this.apad = apad;
    }

    public Integer getPsdcf() {
        return psdcf;
    }

    public void setPsdcf(Integer psdcf) {
        this.psdcf = psdcf;
    }

    public Integer getDiv() {
        return div;
    }

    public void setDiv(Integer div) {
        this.div = div;
    }

    public Integer getCpf() {
        return cpf;
    }

    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }

    public Integer getDpe() {
        return dpe;
    }

    public void setDpe(Integer dpe) {
        this.dpe = dpe;
    }

    public Integer getComu() {
        return comu;
    }

    public void setComu(Integer comu) {
        this.comu = comu;
    }

    public Integer getRdtya() {
        return rdtya;
    }

    public void setRdtya(Integer rdtya) {
        this.rdtya = rdtya;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
