package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P5P15.
 */
public class p5p15 {

    private Long id;
    private Integer tfap;
    private Integer acue;
    private Integer naci;
    private Integer cau;
    private String otro;
    private Integer taap;
    private Integer apcs;
    private Integer adlt;
    private Integer ana;
    private String dfec;
    private Integer depo;
    private Integer hagu;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p5p15() {
    }

    public p5p15(Long id) {
        this.id = id;
    }

    public p5p15(Long id, Integer tfap, Integer acue, Integer naci, Integer cau, String otro, Integer taap, Integer apcs, Integer adlt, Integer ana, String dfec, Integer depo, Integer hagu, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.tfap = tfap;
        this.acue = acue;
        this.naci = naci;
        this.cau = cau;
        this.otro = otro;
        this.taap = taap;
        this.apcs = apcs;
        this.adlt = adlt;
        this.ana = ana;
        this.dfec = dfec;
        this.depo = depo;
        this.hagu = hagu;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTfap() {
        return tfap;
    }

    public void setTfap(Integer tfap) {
        this.tfap = tfap;
    }

    public Integer getAcue() {
        return acue;
    }

    public void setAcue(Integer acue) {
        this.acue = acue;
    }

    public Integer getNaci() {
        return naci;
    }

    public void setNaci(Integer naci) {
        this.naci = naci;
    }

    public Integer getCau() {
        return cau;
    }

    public void setCau(Integer cau) {
        this.cau = cau;
    }

    public String getOtro() {
        return otro;
    }

    public void setOtro(String otro) {
        this.otro = otro;
    }

    public Integer getTaap() {
        return taap;
    }

    public void setTaap(Integer taap) {
        this.taap = taap;
    }

    public Integer getApcs() {
        return apcs;
    }

    public void setApcs(Integer apcs) {
        this.apcs = apcs;
    }

    public Integer getAdlt() {
        return adlt;
    }

    public void setAdlt(Integer adlt) {
        this.adlt = adlt;
    }

    public Integer getAna() {
        return ana;
    }

    public void setAna(Integer ana) {
        this.ana = ana;
    }

    public String getDfec() {
        return dfec;
    }

    public void setDfec(String dfec) {
        this.dfec = dfec;
    }

    public Integer getDepo() {
        return depo;
    }

    public void setDepo(Integer depo) {
        this.depo = depo;
    }

    public Integer getHagu() {
        return hagu;
    }

    public void setHagu(Integer hagu) {
        this.hagu = hagu;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
