package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p5p2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P5P2.
*/
public class p5p2Dao extends AbstractDao<p5p2, Long> {

    public static final String TABLENAME = "P5P2";

    /**
     * Properties of entity p5p2.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Armf = new Property(1, Integer.class, "armf", false, "ARMF");
        public final static Property Omcr = new Property(2, Integer.class, "omcr", false, "OMCR");
        public final static Property Omoc = new Property(3, Integer.class, "omoc", false, "OMOC");
        public final static Property Omoa = new Property(4, Integer.class, "omoa", false, "OMOA");
        public final static Property Niprc = new Property(5, Integer.class, "niprc", false, "NIPRC");
        public final static Property Ndplc = new Property(6, Integer.class, "ndplc", false, "NDPLC");
        public final static Property Origen = new Property(7, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(8, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(9, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p5p2Dao(DaoConfig config) {
        super(config);
    }
    
    public p5p2Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P5P2' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ARMF' INTEGER," + // 1: armf
                "'OMCR' INTEGER," + // 2: omcr
                "'OMOC' INTEGER," + // 3: omoc
                "'OMOA' INTEGER," + // 4: omoa
                "'NIPRC' INTEGER," + // 5: niprc
                "'NDPLC' INTEGER," + // 6: ndplc
                "'ORIGEN' INTEGER," + // 7: origen
                "'ID_FORMULARIO' INTEGER," + // 8: id_formulario
                "'OBSERVACIONES' TEXT);"); // 9: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P5P2'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p5p2 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer armf = entity.getArmf();
        if (armf != null) {
            stmt.bindLong(2, armf);
        }
 
        Integer omcr = entity.getOmcr();
        if (omcr != null) {
            stmt.bindLong(3, omcr);
        }
 
        Integer omoc = entity.getOmoc();
        if (omoc != null) {
            stmt.bindLong(4, omoc);
        }
 
        Integer omoa = entity.getOmoa();
        if (omoa != null) {
            stmt.bindLong(5, omoa);
        }
 
        Integer niprc = entity.getNiprc();
        if (niprc != null) {
            stmt.bindLong(6, niprc);
        }
 
        Integer ndplc = entity.getNdplc();
        if (ndplc != null) {
            stmt.bindLong(7, ndplc);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(8, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(9, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(10, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p5p2 readEntity(Cursor cursor, int offset) {
        p5p2 entity = new p5p2( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // armf
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // omcr
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // omoc
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // omoa
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // niprc
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // ndplc
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // origen
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // id_formulario
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p5p2 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setArmf(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setOmcr(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setOmoc(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setOmoa(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setNiprc(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setNdplc(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setOrigen(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setId_formulario(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setObservaciones(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p5p2 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p5p2 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
