package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P5P5.
 */
public class p5p5 {

    private Long id;
    private Integer armf;
    private Integer salj;
    private Integer cuot;
    private Integer piez;
    private Integer prod;
    private Integer sios;
    private Integer snpc;
    private Integer tacn;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p5p5() {
    }

    public p5p5(Long id) {
        this.id = id;
    }

    public p5p5(Long id, Integer armf, Integer salj, Integer cuot, Integer piez, Integer prod, Integer sios, Integer snpc, Integer tacn, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.armf = armf;
        this.salj = salj;
        this.cuot = cuot;
        this.piez = piez;
        this.prod = prod;
        this.sios = sios;
        this.snpc = snpc;
        this.tacn = tacn;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArmf() {
        return armf;
    }

    public void setArmf(Integer armf) {
        this.armf = armf;
    }

    public Integer getSalj() {
        return salj;
    }

    public void setSalj(Integer salj) {
        this.salj = salj;
    }

    public Integer getCuot() {
        return cuot;
    }

    public void setCuot(Integer cuot) {
        this.cuot = cuot;
    }

    public Integer getPiez() {
        return piez;
    }

    public void setPiez(Integer piez) {
        this.piez = piez;
    }

    public Integer getProd() {
        return prod;
    }

    public void setProd(Integer prod) {
        this.prod = prod;
    }

    public Integer getSios() {
        return sios;
    }

    public void setSios(Integer sios) {
        this.sios = sios;
    }

    public Integer getSnpc() {
        return snpc;
    }

    public void setSnpc(Integer snpc) {
        this.snpc = snpc;
    }

    public Integer getTacn() {
        return tacn;
    }

    public void setTacn(Integer tacn) {
        this.tacn = tacn;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
