package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P5P8.
 */
public class p5p8 {

    private Long id;
    private Integer armf;
    private Integer nstm;
    private Integer nsmt;
    private Integer rptm;
    private Integer jorn;
    private Integer cpdl;
    private Integer noya;
    private Integer fecn;
    private Integer npor;
    private Integer lpor;
    private Integer tlrf;
    private Integer nhat;
    private Integer salr;
    private Integer aefr;
    private String hldm;
    private String hlsm;
    private Integer hnie;
    private Integer tmnr;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p5p8() {
    }

    public p5p8(Long id) {
        this.id = id;
    }

    public p5p8(Long id, Integer armf, Integer nstm, Integer nsmt, Integer rptm, Integer jorn, Integer cpdl, Integer noya, Integer fecn, Integer npor, Integer lpor, Integer tlrf, Integer nhat, Integer salr, Integer aefr, String hldm, String hlsm, Integer hnie, Integer tmnr, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.armf = armf;
        this.nstm = nstm;
        this.nsmt = nsmt;
        this.rptm = rptm;
        this.jorn = jorn;
        this.cpdl = cpdl;
        this.noya = noya;
        this.fecn = fecn;
        this.npor = npor;
        this.lpor = lpor;
        this.tlrf = tlrf;
        this.nhat = nhat;
        this.salr = salr;
        this.aefr = aefr;
        this.hldm = hldm;
        this.hlsm = hlsm;
        this.hnie = hnie;
        this.tmnr = tmnr;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArmf() {
        return armf;
    }

    public void setArmf(Integer armf) {
        this.armf = armf;
    }

    public Integer getNstm() {
        return nstm;
    }

    public void setNstm(Integer nstm) {
        this.nstm = nstm;
    }

    public Integer getNsmt() {
        return nsmt;
    }

    public void setNsmt(Integer nsmt) {
        this.nsmt = nsmt;
    }

    public Integer getRptm() {
        return rptm;
    }

    public void setRptm(Integer rptm) {
        this.rptm = rptm;
    }

    public Integer getJorn() {
        return jorn;
    }

    public void setJorn(Integer jorn) {
        this.jorn = jorn;
    }

    public Integer getCpdl() {
        return cpdl;
    }

    public void setCpdl(Integer cpdl) {
        this.cpdl = cpdl;
    }

    public Integer getNoya() {
        return noya;
    }

    public void setNoya(Integer noya) {
        this.noya = noya;
    }

    public Integer getFecn() {
        return fecn;
    }

    public void setFecn(Integer fecn) {
        this.fecn = fecn;
    }

    public Integer getNpor() {
        return npor;
    }

    public void setNpor(Integer npor) {
        this.npor = npor;
    }

    public Integer getLpor() {
        return lpor;
    }

    public void setLpor(Integer lpor) {
        this.lpor = lpor;
    }

    public Integer getTlrf() {
        return tlrf;
    }

    public void setTlrf(Integer tlrf) {
        this.tlrf = tlrf;
    }

    public Integer getNhat() {
        return nhat;
    }

    public void setNhat(Integer nhat) {
        this.nhat = nhat;
    }

    public Integer getSalr() {
        return salr;
    }

    public void setSalr(Integer salr) {
        this.salr = salr;
    }

    public Integer getAefr() {
        return aefr;
    }

    public void setAefr(Integer aefr) {
        this.aefr = aefr;
    }

    public String getHldm() {
        return hldm;
    }

    public void setHldm(String hldm) {
        this.hldm = hldm;
    }

    public String getHlsm() {
        return hlsm;
    }

    public void setHlsm(String hlsm) {
        this.hlsm = hlsm;
    }

    public Integer getHnie() {
        return hnie;
    }

    public void setHnie(Integer hnie) {
        this.hnie = hnie;
    }

    public Integer getTmnr() {
        return tmnr;
    }

    public void setTmnr(Integer tmnr) {
        this.tmnr = tmnr;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
