package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P5P9.
 */
public class p5p9 {

    private Long id;
    private Integer lcnpm;
    private Integer metf;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p5p9() {
    }

    public p5p9(Long id) {
        this.id = id;
    }

    public p5p9(Long id, Integer lcnpm, Integer metf, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.lcnpm = lcnpm;
        this.metf = metf;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLcnpm() {
        return lcnpm;
    }

    public void setLcnpm(Integer lcnpm) {
        this.lcnpm = lcnpm;
    }

    public Integer getMetf() {
        return metf;
    }

    public void setMetf(Integer metf) {
        this.metf = metf;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
