package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P6P13.
 */
public class p6p13 {

    private Long id;
    private Integer tltq;
    private Integer ltqa;
    private Integer lfse;
    private Integer lfie;
    private Integer eedp;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p6p13() {
    }

    public p6p13(Long id) {
        this.id = id;
    }

    public p6p13(Long id, Integer tltq, Integer ltqa, Integer lfse, Integer lfie, Integer eedp, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.tltq = tltq;
        this.ltqa = ltqa;
        this.lfse = lfse;
        this.lfie = lfie;
        this.eedp = eedp;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTltq() {
        return tltq;
    }

    public void setTltq(Integer tltq) {
        this.tltq = tltq;
    }

    public Integer getLtqa() {
        return ltqa;
    }

    public void setLtqa(Integer ltqa) {
        this.ltqa = ltqa;
    }

    public Integer getLfse() {
        return lfse;
    }

    public void setLfse(Integer lfse) {
        this.lfse = lfse;
    }

    public Integer getLfie() {
        return lfie;
    }

    public void setLfie(Integer lfie) {
        this.lfie = lfie;
    }

    public Integer getEedp() {
        return eedp;
    }

    public void setEedp(Integer eedp) {
        this.eedp = eedp;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
