package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P6P17.
 */
public class p6p17 {

    private Long id;
    private Integer pnms;
    private Integer pdms;
    private Integer euac;
    private Integer nepl;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p6p17() {
    }

    public p6p17(Long id) {
        this.id = id;
    }

    public p6p17(Long id, Integer pnms, Integer pdms, Integer euac, Integer nepl, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.pnms = pnms;
        this.pdms = pdms;
        this.euac = euac;
        this.nepl = nepl;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPnms() {
        return pnms;
    }

    public void setPnms(Integer pnms) {
        this.pnms = pnms;
    }

    public Integer getPdms() {
        return pdms;
    }

    public void setPdms(Integer pdms) {
        this.pdms = pdms;
    }

    public Integer getEuac() {
        return euac;
    }

    public void setEuac(Integer euac) {
        this.euac = euac;
    }

    public Integer getNepl() {
        return nepl;
    }

    public void setNepl(Integer nepl) {
        this.nepl = nepl;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
