package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P6P11.
 */
public class p6p11 {

    private Long id;
    private Integer lfdd;
    private Integer ludl;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p6p11() {
    }

    public p6p11(Long id) {
        this.id = id;
    }

    public p6p11(Long id, Integer lfdd, Integer ludl, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.lfdd = lfdd;
        this.ludl = ludl;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLfdd() {
        return lfdd;
    }

    public void setLfdd(Integer lfdd) {
        this.lfdd = lfdd;
    }

    public Integer getLudl() {
        return ludl;
    }

    public void setLudl(Integer ludl) {
        this.ludl = ludl;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
