package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p6p13;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P6P13.
*/
public class p6p13Dao extends AbstractDao<p6p13, Long> {

    public static final String TABLENAME = "P6P13";

    /**
     * Properties of entity p6p13.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Tltq = new Property(1, Integer.class, "tltq", false, "TLTQ");
        public final static Property Ltqa = new Property(2, Integer.class, "ltqa", false, "LTQA");
        public final static Property Lfse = new Property(3, Integer.class, "lfse", false, "LFSE");
        public final static Property Lfie = new Property(4, Integer.class, "lfie", false, "LFIE");
        public final static Property Eedp = new Property(5, Integer.class, "eedp", false, "EEDP");
        public final static Property Origen = new Property(6, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(7, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(8, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p6p13Dao(DaoConfig config) {
        super(config);
    }
    
    public p6p13Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P6P13' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TLTQ' INTEGER," + // 1: tltq
                "'LTQA' INTEGER," + // 2: ltqa
                "'LFSE' INTEGER," + // 3: lfse
                "'LFIE' INTEGER," + // 4: lfie
                "'EEDP' INTEGER," + // 5: eedp
                "'ORIGEN' INTEGER," + // 6: origen
                "'ID_FORMULARIO' INTEGER," + // 7: id_formulario
                "'OBSERVACIONES' TEXT);"); // 8: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P6P13'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p6p13 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer tltq = entity.getTltq();
        if (tltq != null) {
            stmt.bindLong(2, tltq);
        }
 
        Integer ltqa = entity.getLtqa();
        if (ltqa != null) {
            stmt.bindLong(3, ltqa);
        }
 
        Integer lfse = entity.getLfse();
        if (lfse != null) {
            stmt.bindLong(4, lfse);
        }
 
        Integer lfie = entity.getLfie();
        if (lfie != null) {
            stmt.bindLong(5, lfie);
        }
 
        Integer eedp = entity.getEedp();
        if (eedp != null) {
            stmt.bindLong(6, eedp);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(7, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(8, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(9, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p6p13 readEntity(Cursor cursor, int offset) {
        p6p13 entity = new p6p13( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // tltq
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // ltqa
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // lfse
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // lfie
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // eedp
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // origen
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // id_formulario
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p6p13 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTltq(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setLtqa(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setLfse(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setLfie(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setEedp(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOrigen(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setId_formulario(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setObservaciones(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p6p13 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p6p13 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
