package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p6p11;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P6P11.
*/
public class p6p11Dao extends AbstractDao<p6p11, Long> {

    public static final String TABLENAME = "P6P11";

    /**
     * Properties of entity p6p11.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Lfdd = new Property(1, Integer.class, "lfdd", false, "LFDD");
        public final static Property Ludl = new Property(2, Integer.class, "ludl", false, "LUDL");
        public final static Property Origen = new Property(3, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(4, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(5, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p6p11Dao(DaoConfig config) {
        super(config);
    }
    
    public p6p11Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P6P11' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'LFDD' INTEGER," + // 1: lfdd
                "'LUDL' INTEGER," + // 2: ludl
                "'ORIGEN' INTEGER," + // 3: origen
                "'ID_FORMULARIO' INTEGER," + // 4: id_formulario
                "'OBSERVACIONES' TEXT);"); // 5: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P6P11'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p6p11 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer lfdd = entity.getLfdd();
        if (lfdd != null) {
            stmt.bindLong(2, lfdd);
        }
 
        Integer ludl = entity.getLudl();
        if (ludl != null) {
            stmt.bindLong(3, ludl);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(4, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(5, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(6, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p6p11 readEntity(Cursor cursor, int offset) {
        p6p11 entity = new p6p11( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // lfdd
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // ludl
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // origen
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // id_formulario
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p6p11 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLfdd(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setLudl(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setOrigen(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setId_formulario(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setObservaciones(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p6p11 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p6p11 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
