package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p6p18;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P6P18.
*/
public class p6p18Dao extends AbstractDao<p6p18, Long> {

    public static final String TABLENAME = "P6P18";

    /**
     * Properties of entity p6p18.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Altd = new Property(1, Integer.class, "altd", false, "ALTD");
        public final static Property Iatd = new Property(2, Integer.class, "iatd", false, "IATD");
        public final static Property Lfcc = new Property(3, Integer.class, "lfcc", false, "LFCC");
        public final static Property Ltcl = new Property(4, Integer.class, "ltcl", false, "LTCL");
        public final static Property Rcsa = new Property(5, Integer.class, "rcsa", false, "RCSA");
        public final static Property Pcep = new Property(6, Integer.class, "pcep", false, "PCEP");
        public final static Property Origen = new Property(7, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(8, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(9, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p6p18Dao(DaoConfig config) {
        super(config);
    }
    
    public p6p18Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P6P18' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ALTD' INTEGER," + // 1: altd
                "'IATD' INTEGER," + // 2: iatd
                "'LFCC' INTEGER," + // 3: lfcc
                "'LTCL' INTEGER," + // 4: ltcl
                "'RCSA' INTEGER," + // 5: rcsa
                "'PCEP' INTEGER," + // 6: pcep
                "'ORIGEN' INTEGER," + // 7: origen
                "'ID_FORMULARIO' INTEGER," + // 8: id_formulario
                "'OBSERVACIONES' TEXT);"); // 9: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P6P18'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p6p18 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer altd = entity.getAltd();
        if (altd != null) {
            stmt.bindLong(2, altd);
        }
 
        Integer iatd = entity.getIatd();
        if (iatd != null) {
            stmt.bindLong(3, iatd);
        }
 
        Integer lfcc = entity.getLfcc();
        if (lfcc != null) {
            stmt.bindLong(4, lfcc);
        }
 
        Integer ltcl = entity.getLtcl();
        if (ltcl != null) {
            stmt.bindLong(5, ltcl);
        }
 
        Integer rcsa = entity.getRcsa();
        if (rcsa != null) {
            stmt.bindLong(6, rcsa);
        }
 
        Integer pcep = entity.getPcep();
        if (pcep != null) {
            stmt.bindLong(7, pcep);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(8, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(9, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(10, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p6p18 readEntity(Cursor cursor, int offset) {
        p6p18 entity = new p6p18( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // altd
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // iatd
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // lfcc
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // ltcl
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // rcsa
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // pcep
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // origen
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // id_formulario
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p6p18 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAltd(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setIatd(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setLfcc(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setLtcl(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setRcsa(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setPcep(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setOrigen(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setId_formulario(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setObservaciones(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p6p18 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p6p18 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
