package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P6P20.
 */
public class p6p20 {

    private Long id;
    private Integer fdip;
    private Integer sipd;
    private Integer ecca;
    private Integer mono;
    private Integer lfbs;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p6p20() {
    }

    public p6p20(Long id) {
        this.id = id;
    }

    public p6p20(Long id, Integer fdip, Integer sipd, Integer ecca, Integer mono, Integer lfbs, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.fdip = fdip;
        this.sipd = sipd;
        this.ecca = ecca;
        this.mono = mono;
        this.lfbs = lfbs;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFdip() {
        return fdip;
    }

    public void setFdip(Integer fdip) {
        this.fdip = fdip;
    }

    public Integer getSipd() {
        return sipd;
    }

    public void setSipd(Integer sipd) {
        this.sipd = sipd;
    }

    public Integer getEcca() {
        return ecca;
    }

    public void setEcca(Integer ecca) {
        this.ecca = ecca;
    }

    public Integer getMono() {
        return mono;
    }

    public void setMono(Integer mono) {
        this.mono = mono;
    }

    public Integer getLfbs() {
        return lfbs;
    }

    public void setLfbs(Integer lfbs) {
        this.lfbs = lfbs;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
