package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P6P2.
 */
public class p6p2 {

    private Long id;
    private Integer lfup;
    private Integer eupc;
    private Integer ltcl;
    private Integer lthr;
    private Integer erdd;
    private Integer lfcc;
    private Integer ltop;
    private Integer lmdu;
    private Integer lafr;
    private Integer tetr;
    private Integer ladu;
    private Integer obje;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p6p2() {
    }

    public p6p2(Long id) {
        this.id = id;
    }

    public p6p2(Long id, Integer lfup, Integer eupc, Integer ltcl, Integer lthr, Integer erdd, Integer lfcc, Integer ltop, Integer lmdu, Integer lafr, Integer tetr, Integer ladu, Integer obje, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.lfup = lfup;
        this.eupc = eupc;
        this.ltcl = ltcl;
        this.lthr = lthr;
        this.erdd = erdd;
        this.lfcc = lfcc;
        this.ltop = ltop;
        this.lmdu = lmdu;
        this.lafr = lafr;
        this.tetr = tetr;
        this.ladu = ladu;
        this.obje = obje;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLfup() {
        return lfup;
    }

    public void setLfup(Integer lfup) {
        this.lfup = lfup;
    }

    public Integer getEupc() {
        return eupc;
    }

    public void setEupc(Integer eupc) {
        this.eupc = eupc;
    }

    public Integer getLtcl() {
        return ltcl;
    }

    public void setLtcl(Integer ltcl) {
        this.ltcl = ltcl;
    }

    public Integer getLthr() {
        return lthr;
    }

    public void setLthr(Integer lthr) {
        this.lthr = lthr;
    }

    public Integer getErdd() {
        return erdd;
    }

    public void setErdd(Integer erdd) {
        this.erdd = erdd;
    }

    public Integer getLfcc() {
        return lfcc;
    }

    public void setLfcc(Integer lfcc) {
        this.lfcc = lfcc;
    }

    public Integer getLtop() {
        return ltop;
    }

    public void setLtop(Integer ltop) {
        this.ltop = ltop;
    }

    public Integer getLmdu() {
        return lmdu;
    }

    public void setLmdu(Integer lmdu) {
        this.lmdu = lmdu;
    }

    public Integer getLafr() {
        return lafr;
    }

    public void setLafr(Integer lafr) {
        this.lafr = lafr;
    }

    public Integer getTetr() {
        return tetr;
    }

    public void setTetr(Integer tetr) {
        this.tetr = tetr;
    }

    public Integer getLadu() {
        return ladu;
    }

    public void setLadu(Integer ladu) {
        this.ladu = ladu;
    }

    public Integer getObje() {
        return obje;
    }

    public void setObje(Integer obje) {
        this.obje = obje;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
