package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P7P3.
 */
public class p7p3 {

    private Long id;
    private Integer pypp;
    private Integer ccpp;
    private Integer sccp;
    private Integer lfcp;
    private Integer lfas;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p7p3() {
    }

    public p7p3(Long id) {
        this.id = id;
    }

    public p7p3(Long id, Integer pypp, Integer ccpp, Integer sccp, Integer lfcp, Integer lfas, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.pypp = pypp;
        this.ccpp = ccpp;
        this.sccp = sccp;
        this.lfcp = lfcp;
        this.lfas = lfas;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPypp() {
        return pypp;
    }

    public void setPypp(Integer pypp) {
        this.pypp = pypp;
    }

    public Integer getCcpp() {
        return ccpp;
    }

    public void setCcpp(Integer ccpp) {
        this.ccpp = ccpp;
    }

    public Integer getSccp() {
        return sccp;
    }

    public void setSccp(Integer sccp) {
        this.sccp = sccp;
    }

    public Integer getLfcp() {
        return lfcp;
    }

    public void setLfcp(Integer lfcp) {
        this.lfcp = lfcp;
    }

    public Integer getLfas() {
        return lfas;
    }

    public void setLfas(Integer lfas) {
        this.lfas = lfas;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
