package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P8P2.
 */
public class p8p2 {

    private Long id;
    private Integer lfdd;
    private Integer rcdu;
    private Integer lfrr;
    private Integer lfre;
    private Integer ccui;
    private Integer noco;
    private Integer noge;
    private Integer lafe;
    private Integer caco;
    private Integer prap;
    private Integer tdad;
    private Integer feda;
    private Integer dosi;
    private Integer vtdp;
    private Integer ndlp;
    private Integer ndqa;
    private Integer ndqr;
    private Integer ided;
    private Integer lfme;
    private Integer srya;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p8p2() {
    }

    public p8p2(Long id) {
        this.id = id;
    }

    public p8p2(Long id, Integer lfdd, Integer rcdu, Integer lfrr, Integer lfre, Integer ccui, Integer noco, Integer noge, Integer lafe, Integer caco, Integer prap, Integer tdad, Integer feda, Integer dosi, Integer vtdp, Integer ndlp, Integer ndqa, Integer ndqr, Integer ided, Integer lfme, Integer srya, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.lfdd = lfdd;
        this.rcdu = rcdu;
        this.lfrr = lfrr;
        this.lfre = lfre;
        this.ccui = ccui;
        this.noco = noco;
        this.noge = noge;
        this.lafe = lafe;
        this.caco = caco;
        this.prap = prap;
        this.tdad = tdad;
        this.feda = feda;
        this.dosi = dosi;
        this.vtdp = vtdp;
        this.ndlp = ndlp;
        this.ndqa = ndqa;
        this.ndqr = ndqr;
        this.ided = ided;
        this.lfme = lfme;
        this.srya = srya;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLfdd() {
        return lfdd;
    }

    public void setLfdd(Integer lfdd) {
        this.lfdd = lfdd;
    }

    public Integer getRcdu() {
        return rcdu;
    }

    public void setRcdu(Integer rcdu) {
        this.rcdu = rcdu;
    }

    public Integer getLfrr() {
        return lfrr;
    }

    public void setLfrr(Integer lfrr) {
        this.lfrr = lfrr;
    }

    public Integer getLfre() {
        return lfre;
    }

    public void setLfre(Integer lfre) {
        this.lfre = lfre;
    }

    public Integer getCcui() {
        return ccui;
    }

    public void setCcui(Integer ccui) {
        this.ccui = ccui;
    }

    public Integer getNoco() {
        return noco;
    }

    public void setNoco(Integer noco) {
        this.noco = noco;
    }

    public Integer getNoge() {
        return noge;
    }

    public void setNoge(Integer noge) {
        this.noge = noge;
    }

    public Integer getLafe() {
        return lafe;
    }

    public void setLafe(Integer lafe) {
        this.lafe = lafe;
    }

    public Integer getCaco() {
        return caco;
    }

    public void setCaco(Integer caco) {
        this.caco = caco;
    }

    public Integer getPrap() {
        return prap;
    }

    public void setPrap(Integer prap) {
        this.prap = prap;
    }

    public Integer getTdad() {
        return tdad;
    }

    public void setTdad(Integer tdad) {
        this.tdad = tdad;
    }

    public Integer getFeda() {
        return feda;
    }

    public void setFeda(Integer feda) {
        this.feda = feda;
    }

    public Integer getDosi() {
        return dosi;
    }

    public void setDosi(Integer dosi) {
        this.dosi = dosi;
    }

    public Integer getVtdp() {
        return vtdp;
    }

    public void setVtdp(Integer vtdp) {
        this.vtdp = vtdp;
    }

    public Integer getNdlp() {
        return ndlp;
    }

    public void setNdlp(Integer ndlp) {
        this.ndlp = ndlp;
    }

    public Integer getNdqa() {
        return ndqa;
    }

    public void setNdqa(Integer ndqa) {
        this.ndqa = ndqa;
    }

    public Integer getNdqr() {
        return ndqr;
    }

    public void setNdqr(Integer ndqr) {
        this.ndqr = ndqr;
    }

    public Integer getIded() {
        return ided;
    }

    public void setIded(Integer ided) {
        this.ided = ided;
    }

    public Integer getLfme() {
        return lfme;
    }

    public void setLfme(Integer lfme) {
        this.lfme = lfme;
    }

    public Integer getSrya() {
        return srya;
    }

    public void setSrya(Integer srya) {
        this.srya = srya;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
