package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P8P3.
 */
public class p8p3 {

    private Long id;
    private Integer lfdi;
    private Integer silp;
    private Integer ccen;
    private Integer ceen;
    private Integer enep;
    private Integer lfda;
    private Integer origen;
    private String obser;
    private Integer id_formulario;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p8p3() {
    }

    public p8p3(Long id) {
        this.id = id;
    }

    public p8p3(Long id, Integer lfdi, Integer silp, Integer ccen, Integer ceen, Integer enep, Integer lfda, Integer origen, String obser, Integer id_formulario) {
        this.id = id;
        this.lfdi = lfdi;
        this.silp = silp;
        this.ccen = ccen;
        this.ceen = ceen;
        this.enep = enep;
        this.lfda = lfda;
        this.origen = origen;
        this.obser = obser;
        this.id_formulario = id_formulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLfdi() {
        return lfdi;
    }

    public void setLfdi(Integer lfdi) {
        this.lfdi = lfdi;
    }

    public Integer getSilp() {
        return silp;
    }

    public void setSilp(Integer silp) {
        this.silp = silp;
    }

    public Integer getCcen() {
        return ccen;
    }

    public void setCcen(Integer ccen) {
        this.ccen = ccen;
    }

    public Integer getCeen() {
        return ceen;
    }

    public void setCeen(Integer ceen) {
        this.ceen = ceen;
    }

    public Integer getEnep() {
        return enep;
    }

    public void setEnep(Integer enep) {
        this.enep = enep;
    }

    public Integer getLfda() {
        return lfda;
    }

    public void setLfda(Integer lfda) {
        this.lfda = lfda;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public String getObser() {
        return obser;
    }

    public void setObser(String obser) {
        this.obser = obser;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
