package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p8p5;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P8P5.
*/
public class p8p5Dao extends AbstractDao<p8p5, Long> {

    public static final String TABLENAME = "P8P5";

    /**
     * Properties of entity p8p5.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Deup = new Property(1, Integer.class, "deup", false, "DEUP");
        public final static Property Eupp = new Property(2, Integer.class, "eupp", false, "EUPP");
        public final static Property Pprl = new Property(3, Integer.class, "pprl", false, "PPRL");
        public final static Property Seep = new Property(4, Integer.class, "seep", false, "SEEP");
        public final static Property Origen = new Property(5, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(6, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(7, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public p8p5Dao(DaoConfig config) {
        super(config);
    }
    
    public p8p5Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P8P5' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DEUP' INTEGER," + // 1: deup
                "'EUPP' INTEGER," + // 2: eupp
                "'PPRL' INTEGER," + // 3: pprl
                "'SEEP' INTEGER," + // 4: seep
                "'ORIGEN' INTEGER," + // 5: origen
                "'OBSER' TEXT," + // 6: obser
                "'ID_FORMULARIO' INTEGER);"); // 7: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P8P5'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p8p5 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer deup = entity.getDeup();
        if (deup != null) {
            stmt.bindLong(2, deup);
        }
 
        Integer eupp = entity.getEupp();
        if (eupp != null) {
            stmt.bindLong(3, eupp);
        }
 
        Integer pprl = entity.getPprl();
        if (pprl != null) {
            stmt.bindLong(4, pprl);
        }
 
        Integer seep = entity.getSeep();
        if (seep != null) {
            stmt.bindLong(5, seep);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(6, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(7, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(8, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p8p5 readEntity(Cursor cursor, int offset) {
        p8p5 entity = new p8p5( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // deup
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // eupp
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // pprl
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // seep
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // origen
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // obser
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p8p5 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeup(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setEupp(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setPprl(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setSeep(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOrigen(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setObser(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setId_formulario(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p8p5 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p8p5 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
