package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p8p6;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P8P6.
*/
public class p8p6Dao extends AbstractDao<p8p6, Long> {

    public static final String TABLENAME = "P8P6";

    /**
     * Properties of entity p8p6.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Dtmp = new Property(1, Integer.class, "dtmp", false, "DTMP");
        public final static Property Seic = new Property(2, Integer.class, "seic", false, "SEIC");
        public final static Property Nshi = new Property(3, Integer.class, "nshi", false, "NSHI");
        public final static Property Sdye = new Property(4, Integer.class, "sdye", false, "SDYE");
        public final static Property Origen = new Property(5, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(6, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(7, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p8p6Dao(DaoConfig config) {
        super(config);
    }
    
    public p8p6Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P8P6' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DTMP' INTEGER," + // 1: dtmp
                "'SEIC' INTEGER," + // 2: seic
                "'NSHI' INTEGER," + // 3: nshi
                "'SDYE' INTEGER," + // 4: sdye
                "'ORIGEN' INTEGER," + // 5: origen
                "'ID_FORMULARIO' INTEGER," + // 6: id_formulario
                "'OBSERVACIONES' TEXT);"); // 7: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P8P6'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p8p6 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer dtmp = entity.getDtmp();
        if (dtmp != null) {
            stmt.bindLong(2, dtmp);
        }
 
        Integer seic = entity.getSeic();
        if (seic != null) {
            stmt.bindLong(3, seic);
        }
 
        Integer nshi = entity.getNshi();
        if (nshi != null) {
            stmt.bindLong(4, nshi);
        }
 
        Integer sdye = entity.getSdye();
        if (sdye != null) {
            stmt.bindLong(5, sdye);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(6, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(7, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(8, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p8p6 readEntity(Cursor cursor, int offset) {
        p8p6 entity = new p8p6( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // dtmp
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // seic
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // nshi
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // sdye
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // origen
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // id_formulario
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p8p6 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDtmp(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSeic(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setNshi(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setSdye(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOrigen(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setId_formulario(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setObservaciones(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p8p6 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p8p6 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
