package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p8p8;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P8P8.
*/
public class p8p8Dao extends AbstractDao<p8p8, Long> {

    public static final String TABLENAME = "P8P8";

    /**
     * Properties of entity p8p8.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nslp = new Property(1, Integer.class, "nslp", false, "NSLP");
        public final static Property Udfp = new Property(2, Integer.class, "udfp", false, "UDFP");
        public final static Property Selp = new Property(3, Integer.class, "selp", false, "SELP");
        public final static Property Origen = new Property(4, Integer.class, "origen", false, "ORIGEN");
        public final static Property Id_formulario = new Property(5, Integer.class, "id_formulario", false, "ID_FORMULARIO");
        public final static Property Observaciones = new Property(6, String.class, "observaciones", false, "OBSERVACIONES");
    };


    public p8p8Dao(DaoConfig config) {
        super(config);
    }
    
    public p8p8Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P8P8' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NSLP' INTEGER," + // 1: nslp
                "'UDFP' INTEGER," + // 2: udfp
                "'SELP' INTEGER," + // 3: selp
                "'ORIGEN' INTEGER," + // 4: origen
                "'ID_FORMULARIO' INTEGER," + // 5: id_formulario
                "'OBSERVACIONES' TEXT);"); // 6: observaciones
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P8P8'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p8p8 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer nslp = entity.getNslp();
        if (nslp != null) {
            stmt.bindLong(2, nslp);
        }
 
        Integer udfp = entity.getUdfp();
        if (udfp != null) {
            stmt.bindLong(3, udfp);
        }
 
        Integer selp = entity.getSelp();
        if (selp != null) {
            stmt.bindLong(4, selp);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(5, origen);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(6, id_formulario);
        }
 
        String observaciones = entity.getObservaciones();
        if (observaciones != null) {
            stmt.bindString(7, observaciones);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p8p8 readEntity(Cursor cursor, int offset) {
        p8p8 entity = new p8p8( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // nslp
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // udfp
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // selp
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // origen
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // id_formulario
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // observaciones
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p8p8 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNslp(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setUdfp(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setSelp(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setOrigen(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setId_formulario(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setObservaciones(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p8p8 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p8p8 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
