package naturacert.baumsoft.dev.naturacert;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import naturacert.baumsoft.dev.naturacert.p9p1;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table P9P1.
*/
public class p9p1Dao extends AbstractDao<p9p1, Long> {

    public static final String TABLENAME = "P9P1";

    /**
     * Properties of entity p9p1.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fepce = new Property(1, Integer.class, "fepce", false, "FEPCE");
        public final static Property Fcpce = new Property(2, Integer.class, "fcpce", false, "FCPCE");
        public final static Property Epes = new Property(3, Integer.class, "epes", false, "EPES");
        public final static Property Ifas = new Property(4, Integer.class, "ifas", false, "IFAS");
        public final static Property Uecv = new Property(5, Integer.class, "uecv", false, "UECV");
        public final static Property Origen = new Property(6, Integer.class, "origen", false, "ORIGEN");
        public final static Property Obser = new Property(7, String.class, "obser", false, "OBSER");
        public final static Property Id_formulario = new Property(8, Integer.class, "id_formulario", false, "ID_FORMULARIO");
    };


    public p9p1Dao(DaoConfig config) {
        super(config);
    }
    
    public p9p1Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'P9P1' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FEPCE' INTEGER," + // 1: fepce
                "'FCPCE' INTEGER," + // 2: fcpce
                "'EPES' INTEGER," + // 3: epes
                "'IFAS' INTEGER," + // 4: ifas
                "'UECV' INTEGER," + // 5: uecv
                "'ORIGEN' INTEGER," + // 6: origen
                "'OBSER' TEXT," + // 7: obser
                "'ID_FORMULARIO' INTEGER);"); // 8: id_formulario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'P9P1'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, p9p1 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer fepce = entity.getFepce();
        if (fepce != null) {
            stmt.bindLong(2, fepce);
        }
 
        Integer fcpce = entity.getFcpce();
        if (fcpce != null) {
            stmt.bindLong(3, fcpce);
        }
 
        Integer epes = entity.getEpes();
        if (epes != null) {
            stmt.bindLong(4, epes);
        }
 
        Integer ifas = entity.getIfas();
        if (ifas != null) {
            stmt.bindLong(5, ifas);
        }
 
        Integer uecv = entity.getUecv();
        if (uecv != null) {
            stmt.bindLong(6, uecv);
        }
 
        Integer origen = entity.getOrigen();
        if (origen != null) {
            stmt.bindLong(7, origen);
        }
 
        String obser = entity.getObser();
        if (obser != null) {
            stmt.bindString(8, obser);
        }
 
        Integer id_formulario = entity.getId_formulario();
        if (id_formulario != null) {
            stmt.bindLong(9, id_formulario);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public p9p1 readEntity(Cursor cursor, int offset) {
        p9p1 entity = new p9p1( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // fepce
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // fcpce
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // epes
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // ifas
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // uecv
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // origen
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // obser
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // id_formulario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, p9p1 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFepce(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setFcpce(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setEpes(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setIfas(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setUecv(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setOrigen(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setObser(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setId_formulario(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(p9p1 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(p9p1 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
