package naturacert.baumsoft.dev.naturacert;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table P9P3.
 */
public class p9p3 {

    private Long id;
    private Integer fdec;
    private Integer fuev;
    private Integer fcec;
    private Integer acae;
    private Integer adec;
    private Integer croa;
    private Integer mach;
    private Integer guad;
    private Integer herb;
    private Integer origen;
    private Integer id_formulario;
    private String observaciones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public p9p3() {
    }

    public p9p3(Long id) {
        this.id = id;
    }

    public p9p3(Long id, Integer fdec, Integer fuev, Integer fcec, Integer acae, Integer adec, Integer croa, Integer mach, Integer guad, Integer herb, Integer origen, Integer id_formulario, String observaciones) {
        this.id = id;
        this.fdec = fdec;
        this.fuev = fuev;
        this.fcec = fcec;
        this.acae = acae;
        this.adec = adec;
        this.croa = croa;
        this.mach = mach;
        this.guad = guad;
        this.herb = herb;
        this.origen = origen;
        this.id_formulario = id_formulario;
        this.observaciones = observaciones;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFdec() {
        return fdec;
    }

    public void setFdec(Integer fdec) {
        this.fdec = fdec;
    }

    public Integer getFuev() {
        return fuev;
    }

    public void setFuev(Integer fuev) {
        this.fuev = fuev;
    }

    public Integer getFcec() {
        return fcec;
    }

    public void setFcec(Integer fcec) {
        this.fcec = fcec;
    }

    public Integer getAcae() {
        return acae;
    }

    public void setAcae(Integer acae) {
        this.acae = acae;
    }

    public Integer getAdec() {
        return adec;
    }

    public void setAdec(Integer adec) {
        this.adec = adec;
    }

    public Integer getCroa() {
        return croa;
    }

    public void setCroa(Integer croa) {
        this.croa = croa;
    }

    public Integer getMach() {
        return mach;
    }

    public void setMach(Integer mach) {
        this.mach = mach;
    }

    public Integer getGuad() {
        return guad;
    }

    public void setGuad(Integer guad) {
        this.guad = guad;
    }

    public Integer getHerb() {
        return herb;
    }

    public void setHerb(Integer herb) {
        this.herb = herb;
    }

    public Integer getOrigen() {
        return origen;
    }

    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    public Integer getId_formulario() {
        return id_formulario;
    }

    public void setId_formulario(Integer id_formulario) {
        this.id_formulario = id_formulario;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
